modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/CyberDay1/FTBQuestExternalApp/issues"
license="MIT"

[[mods]]
modId="ftbqprobe"
version="${file.jarVersion}"
displayName="FTB Quests Registry Probe"
description='''Dumps NeoForge runtime registry and language data when a server starts.'''

[[dependencies.ftbqprobe]]
modId="neoforge"
type="required"
versionRange="[21.1.0,)"
ordering="NONE"
side="SERVER"

[[dependencies.ftbqprobe]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="SERVER"
