// <auto-generated/>
using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage(
    "Naming",
    "CA1707:Identifiers should not contain underscores",
    Justification = "Unit tests use underscores to describe behavior.",
    Scope = "namespaceanddescendants",
    Target = "FTBQuests.Tests")]
