// <copyright file="GlobalSuppressions.cs" company="CyberDay1">
// Copyright (c) CyberDay1. All rights reserved.
// </copyright>

// <auto-generated/>
using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage(
    "Naming",
    "CA1707:Identifiers should not contain underscores",
    Justification = "Unit tests use underscores to describe behavior.",
    Scope = "namespaceanddescendants",
    Target = "FTBQuests.Tests")]
